import { Check, ChevronRight, PackagePlus, Rocket, Sparkles, Trash2, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { apiRequest, AuthSession } from "../lib/api";
type Step={code:string;label:string;completed:boolean};type Onboarding={businessType:string|null;phone:string|null;address:string|null;logoUrl:string|null;onboardingDismissed:boolean;demoProductCount:number;completedSteps:number;totalSteps:number;steps:Step[]};
const targets:Record<string,string>={product:"Productos",inventory:"Inventario",cash:"Punto de venta",sale:"Punto de venta",user:"Usuarios"};
export function OnboardingPanel({session,onNavigate}:{session:AuthSession;onNavigate:(page:string)=>void}){
 const [data,setData]=useState<Onboarding|null>(null),[profileOpen,setProfileOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(){try{setData(await apiRequest<Onboarding>("/api/v1/onboarding",{},session))}catch(e){setError(e instanceof Error?e.message:"No pudimos consultar tu progreso.")}}
 useEffect(()=>{void load()},[session]);
 async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{await apiRequest<void>("/api/v1/onboarding/profile",{method:"PUT",body:JSON.stringify(Object.fromEntries(form.entries()))},session);setProfileOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:"No pudimos guardar los datos.")}finally{setBusy(false)}}
 async function preference(body:{printingConfigured?:boolean;dismissed?:boolean}){await apiRequest<void>("/api/v1/onboarding/preferences",{method:"PUT",body:JSON.stringify(body)},session);await load()}
 async function demo(remove=false){setBusy(true);setError("");setMessage("");try{await apiRequest<void|{products:number}>("/api/v1/onboarding/demo-catalog",{method:remove?"DELETE":"POST",...(remove?{}:{body:JSON.stringify({businessType:data?.businessType??"otro"})})},session);setMessage(remove?"El catálogo de ejemplo fue eliminado.":"Agregamos productos de ejemplo. Puedes modificarlos o eliminarlos después.");await load()}catch(e){setError(e instanceof Error?e.message:"No pudimos actualizar los ejemplos.")}finally{setBusy(false)}}
 async function act(step:Step){if(step.code==="profile"){setProfileOpen(true);return}if(step.code==="printing"){await preference({printingConfigured:true});onNavigate("Configuración");return}const target=targets[step.code];if(target)onNavigate(target)}
 if(!data||data.completedSteps===data.totalSteps)return null;if(data.onboardingDismissed)return <button className="onboarding-reopen" onClick={()=>void preference({dismissed:false})}><Rocket/><span><strong>Continuar configuración</strong><small>{data.completedSteps} de {data.totalSteps} tareas completadas</small></span><ChevronRight/></button>;const progress=Math.round(data.completedSteps/data.totalSteps*100);
 return <><section className="onboarding-panel"><div className="onboarding-top"><span><Rocket/></span><div><p className="eyebrow">PRIMEROS PASOS</p><h2>Prepara tu negocio para la primera venta</h2><p>{data.completedSteps} de {data.totalSteps} tareas completadas</p></div><button title="Ocultar por ahora" onClick={()=>void preference({dismissed:true})}><X/></button></div><div className="onboarding-progress"><i style={{width:`${progress}%`}}/><span>{progress}%</span></div>{error&&<div className="form-error">{error}</div>}{message&&<div className="form-success">{message}</div>}<div className="onboarding-steps">{data.steps.map(step=><button className={step.completed?"completed":""} key={step.code} onClick={()=>void act(step)}><span>{step.completed?<Check/>:<i/>}</span><strong>{step.label}</strong><ChevronRight/></button>)}</div><div className="demo-actions"><div><Sparkles/><span><strong>¿Quieres explorar primero?</strong><small>Crea productos de ejemplo según tu giro.</small></span></div>{data.demoProductCount?<button disabled={busy} onClick={()=>void demo(true)}><Trash2/>Eliminar ejemplos</button>:<button disabled={busy} onClick={()=>void demo()}><PackagePlus/>Crear datos de ejemplo</button>}</div></section>
 {profileOpen&&<div className="modal-layer"><form className="onboarding-modal" onSubmit={saveProfile}><button type="button" className="close-form" onClick={()=>setProfileOpen(false)}><X/></button><p className="eyebrow">CONFIGURACIÓN INICIAL</p><h2>Cuéntanos sobre tu negocio</h2><p>Usaremos estos datos para personalizar tu experiencia.</p><label>Giro<select name="businessType" required defaultValue={data.businessType??""}><option value="" disabled>Selecciona</option><option value="boutique">Boutique o ropa</option><option value="calzado">Calzado</option><option value="papeleria">Papelería</option><option value="regalos">Regalos y accesorios</option><option value="otro">Otro comercio</option></select></label><label>Teléfono<input name="phone" required defaultValue={data.phone??""}/></label><label>Dirección<input name="address" defaultValue={data.address??""}/></label><label>URL del logo <small>(opcional)</small><input name="logoUrl" type="url" defaultValue={data.logoUrl??""}/></label>{error&&<div className="form-error">{error}</div>}<button className="button primary" disabled={busy}>{busy?"Guardando...":"Guardar y continuar"}</button></form></div>}</>;
}
