import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Building2, LogOut, RefreshCw, Search, Users, UserRoundPlus, BadgeDollarSign } from "lucide-react";

type AdminSession = { accessToken: string; expiresAtUtc: string; email: string };
type Tenant = { id:string; name:string; slug:string; planCode:string; subscriptionStatus:string; trialEndsAtUtc:string; currentPeriodEndsAtUtc:string|null; subscriptionNotes:string|null; isActive:boolean; createdAtUtc:string; users:number; branches:number; products:number; lastSaleAtUtc:string|null };
type Lead = { id:string; contactName:string; businessName:string; phone:string; email:string|null; city:string|null; businessType:string|null; status:string; createdAtUtc:string };
type Dashboard = { summary:{total:number;active:number;trials:number;pastDue:number;newLeads:number}; tenants:Tenant[]; leads:Lead[] };
const key = "vendemefacil.platform-session";

export function PlatformAdminPage({ onBack }:{onBack:()=>void}) {
  const [session,setSession] = useState<AdminSession|null>(()=>{try{const value=JSON.parse(localStorage.getItem(key)??"null");return value&&new Date(value.expiresAtUtc)>new Date()?value:null}catch{return null}});
  const [data,setData] = useState<Dashboard|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [query,setQuery]=useState(""); const [view,setView]=useState<"businesses"|"leads">("businesses");
  async function request(path:string, options:RequestInit={}) { const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(session?{Authorization:`Bearer ${session.accessToken}`}:{})}}); if(!response.ok) throw new Error(response.status===401?"La sesión no es válida.":"No pudimos completar la operación."); return response.status===204?null:response.json(); }
  async function load(){if(!session)return;setBusy(true);try{setData(await request("/api/platform/dashboard"));setError("")}catch(e){setError(e instanceof Error?e.message:"Error inesperado")}finally{setBusy(false)}}
  useEffect(()=>{void load()},[session]);
  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/auth/platform-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(form.entries()))});if(!response.ok)throw new Error("El correo o la contraseña no son correctos.");const value=await response.json();localStorage.setItem(key,JSON.stringify(value));setSession(value)}catch(e){setError(e instanceof Error?e.message:"No pudimos iniciar sesión.")}finally{setBusy(false)}}
  async function updateTenant(tenant:Tenant, field:"plan"|"status"|"active", value:string|boolean){await request(`/api/platform/tenants/${tenant.id}/subscription`,{method:"PUT",body:JSON.stringify({planCode:field==="plan"?value:tenant.planCode,status:field==="status"?value:tenant.subscriptionStatus,trialEndsAtUtc:tenant.trialEndsAtUtc,currentPeriodEndsAtUtc:tenant.currentPeriodEndsAtUtc,notes:tenant.subscriptionNotes,isActive:field==="active"?value:tenant.isActive})});await load()}
  async function updateLead(lead:Lead,status:string){await request(`/api/platform/leads/${lead.id}/status`,{method:"PUT",body:JSON.stringify({status})});await load()}
  function logout(){localStorage.removeItem(key);setSession(null);setData(null)}
  if(!session)return <main className="platform-login"><button onClick={onBack}><ArrowLeft/> Volver al sitio</button><form onSubmit={login}><span>VF</span><h1>Administración</h1><p>Acceso exclusivo del equipo de Véndeme Fácil.</p><label>Correo<input name="email" type="email" required autoComplete="username"/></label><label>Contraseña<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<div className="admin-error">{error}</div>}<button className="admin-primary" disabled={busy}>{busy?"Entrando...":"Iniciar sesión"}</button></form></main>;
  const tenants=(data?.tenants??[]).filter(x=>`${x.name} ${x.slug}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="platform-shell"><aside><div className="admin-brand"><span>VF</span><strong>Administración</strong></div><button className={view==="businesses"?"active":""} onClick={()=>setView("businesses")}><Building2/>Negocios</button><button className={view==="leads"?"active":""} onClick={()=>setView("leads")}><UserRoundPlus/>Prospectos</button><button className="admin-logout" onClick={logout}><LogOut/>Cerrar sesión</button></aside><main><header><div><small>VÉNDEME FÁCIL</small><h1>{view==="businesses"?"Negocios":"Prospectos"}</h1></div><button onClick={()=>void load()} disabled={busy}><RefreshCw/>Actualizar</button></header>{error&&<div className="admin-error">{error}</div>}
  <section className="admin-metrics"><article><Building2/><span>Negocios<strong>{data?.summary.total??0}</strong></span></article><article><Users/><span>Activos<strong>{data?.summary.active??0}</strong></span></article><article><BadgeDollarSign/><span>En prueba<strong>{data?.summary.trials??0}</strong></span></article><article><UserRoundPlus/><span>Prospectos nuevos<strong>{data?.summary.newLeads??0}</strong></span></article></section>
  {view==="businesses"?<><div className="admin-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar negocio..."/></div><div className="admin-table"><table><thead><tr><th>Negocio</th><th>Uso</th><th>Plan</th><th>Suscripción</th><th>Última venta</th><th>Acceso</th></tr></thead><tbody>{tenants.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>{x.slug} · Alta {new Date(x.createdAtUtc).toLocaleDateString("es-MX")}</small></td><td><span>{x.users} usuarios · {x.branches} suc. · {x.products} productos</span></td><td><select value={x.planCode} onChange={e=>void updateTenant(x,"plan",e.target.value)}><option value="esencial">Esencial $199</option><option value="negocio">Negocio $499</option><option value="pro">Pro $799</option></select></td><td><select value={x.subscriptionStatus} onChange={e=>void updateTenant(x,"status",e.target.value)}><option value="Trial">Prueba</option><option value="Active">Activo</option><option value="PastDue">Pago vencido</option><option value="Suspended">Suspendido</option><option value="Cancelled">Cancelado</option></select></td><td>{x.lastSaleAtUtc?new Date(x.lastSaleAtUtc).toLocaleDateString("es-MX"):"Sin ventas"}</td><td><button className={x.isActive?"status-on":"status-off"} onClick={()=>void updateTenant(x,"active",!x.isActive)}>{x.isActive?"Activo":"Bloqueado"}</button></td></tr>)}</tbody></table></div></>:<div className="admin-table"><table><thead><tr><th>Prospecto</th><th>Contacto</th><th>Giro / ciudad</th><th>Fecha</th><th>Estado</th></tr></thead><tbody>{(data?.leads??[]).map(x=><tr key={x.id}><td><strong>{x.contactName}</strong><small>{x.businessName}</small></td><td><a href={`https://wa.me/${x.phone.replace(/\D/g,"")}`} target="_blank" rel="noreferrer">{x.phone}</a><small>{x.email}</small></td><td>{x.businessType??"—"}<small>{x.city}</small></td><td>{new Date(x.createdAtUtc).toLocaleDateString("es-MX")}</td><td><select value={x.status} onChange={e=>void updateLead(x,e.target.value)}><option value="New">Nuevo</option><option value="Contacted">Contactado</option><option value="DemoScheduled">Demo agendada</option><option value="Trial">En prueba</option><option value="Converted">Convertido</option><option value="NotInterested">No interesado</option></select></td></tr>)}</tbody></table></div>}</main></div>;
}
