import { CalendarDays, Check, Clock3, ReceiptText, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { apiRequest, AuthSession } from "../lib/api";
type Payment={id:string;amount:number;method:string;reference:string|null;paidAtUtc:string;periodStartsAtUtc:string;periodEndsAtUtc:string};
type Subscription={planCode:string;subscriptionStatus:string;trialEndsAtUtc:string;currentPeriodEndsAtUtc:string|null;graceEndsAtUtc:string|null;payments:Payment[]};
const plans:Record<string,{name:string;price:number;features:string[]}>= {esencial:{name:"Esencial",price:199,features:["Punto de venta e inventario","Clientes, tickets y cortes","1 usuario y 1 sucursal"]},negocio:{name:"Negocio",price:499,features:["Apartados y reportes completos","Importación, roles y permisos","5 usuarios y 2 sucursales"]},pro:{name:"Pro",price:799,features:["Reportes consolidados","Personalización de marca","15 usuarios y 5 sucursales"]}};
const labels:Record<string,string>={Trial:"Periodo de prueba",Active:"Suscripción activa",PastDue:"Pago pendiente",Suspended:"Suspendida",Cancelled:"Cancelada"};
const money=new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"});
export function SubscriptionPage({session}:{session:AuthSession}){
 const [data,setData]=useState<Subscription|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState("");
 useEffect(()=>{apiRequest<Subscription>("/api/v1/subscription",{},session).then(setData).catch(e=>setError(e instanceof Error?e.message:"No pudimos consultar tu plan."))},[session]);
 async function requestChange(planCode:string){setBusy(planCode);setError("");setMessage("");try{const result=await apiRequest<{message:string}>("/api/v1/subscription/change-request",{method:"POST",body:JSON.stringify({planCode})},session);setMessage(result.message)}catch(e){setError(e instanceof Error?e.message:"No pudimos enviar la solicitud.")}finally{setBusy("")}}
 if(!data)return <div className="content">{error?<div className="form-error">{error}</div>:<p>Cargando tu suscripción...</p>}</div>;
 const plan=plans[data.planCode]??plans.negocio,end=data.subscriptionStatus==="Trial"?data.trialEndsAtUtc:data.currentPeriodEndsAtUtc,days=end?Math.ceil((new Date(end).getTime()-Date.now())/86400000):null;
 return <div className="content subscription-page"><section className="subscription-heading"><div><p className="eyebrow">CUENTA Y FACTURACIÓN</p><h1>Mi plan</h1><p>Consulta tu prueba, vigencia y pagos registrados.</p></div></section>{error&&<div className="form-error">{error}</div>}{message&&<div className="form-success">{message}</div>}
 <section className="subscription-hero"><div><span className="subscription-status"><ShieldCheck/>{labels[data.subscriptionStatus]??data.subscriptionStatus}</span><h2>Plan {plan.name}</h2><div className="subscription-price"><strong>{money.format(plan.price)}</strong><span>MXN al mes</span></div><ul>{plan.features.map(x=><li key={x}><Check/>{x}</li>)}</ul></div><aside><Clock3/><span>{days!==null&&days>=0?`${days} días restantes`:days!==null?"Periodo finalizado":"Sin fecha de vencimiento"}</span><strong>{end?new Date(end).toLocaleDateString("es-MX",{day:"numeric",month:"long",year:"numeric"}):"—"}</strong><small>{data.graceEndsAtUtc&&<>Acceso de gracia hasta el {new Date(data.graceEndsAtUtc).toLocaleDateString("es-MX")}.</>}</small></aside></section>
 <section className="plan-options"><h2>Planes disponibles</h2><div>{Object.entries(plans).map(([code,item])=><article className={code===data.planCode?"current":""} key={code}><h3>{item.name}</h3><strong>{money.format(item.price)}<small>/mes</small></strong><p>{code===data.planCode?"Tu plan actual":"Solicita el cambio sin perder tu información."}</p><button disabled={code===data.planCode||!!busy} onClick={()=>void requestChange(code)}>{code===data.planCode?"Plan actual":busy===code?"Enviando...":"Solicitar cambio"}</button></article>)}</div></section>
 <section className="payment-history"><div><ReceiptText/><span><h2>Historial de pagos</h2><p>Pagos registrados por nuestro equipo.</p></span></div>{data.payments.length?<table><thead><tr><th>Fecha</th><th>Periodo</th><th>Método</th><th>Referencia</th><th>Importe</th></tr></thead><tbody>{data.payments.map(x=><tr key={x.id}><td>{new Date(x.paidAtUtc).toLocaleDateString("es-MX")}</td><td>{new Date(x.periodStartsAtUtc).toLocaleDateString("es-MX")} – {new Date(x.periodEndsAtUtc).toLocaleDateString("es-MX")}</td><td>{x.method}</td><td>{x.reference??"—"}</td><td><strong>{money.format(x.amount)}</strong></td></tr>)}</tbody></table>:<div className="empty-payments"><CalendarDays/><p>Todavía no hay pagos registrados. Tu periodo de prueba no requiere tarjeta.</p></div>}</section></div>;
}
